/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as appPantryRouteImport } from './routes/(app)/pantry'
import { Route as appProfileRouteImport } from './routes/(app)/profile'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as ApiIngestSplatRouteImport } from './routes/api/ingest.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const appPantryRoute = appPantryRouteImport.update({
  id: '/(app)/pantry',
  path: '/pantry',
  getParentRoute: () => rootRouteImport,
} as any)
const appProfileRoute = appProfileRouteImport.update({
  id: '/(app)/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIngestSplatRoute = ApiIngestSplatRouteImport.update({
  id: '/api/ingest/$',
  path: '/api/ingest/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pantry': typeof appPantryRoute
  '/profile': typeof appProfileRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/ingest/$': typeof ApiIngestSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pantry': typeof appPantryRoute
  '/profile': typeof appProfileRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/ingest/$': typeof ApiIngestSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(app)/pantry': typeof appPantryRoute
  '/(app)/profile': typeof appProfileRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/ingest/$': typeof ApiIngestSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/pantry'
    | '/profile'
    | '/auth/login'
    | '/auth/signup'
    | '/api/auth/$'
    | '/api/ingest/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/pantry'
    | '/profile'
    | '/auth/login'
    | '/auth/signup'
    | '/api/auth/$'
    | '/api/ingest/$'
  id:
    | '__root__'
    | '/'
    | '/(app)/pantry'
    | '/(app)/profile'
    | '/auth/login'
    | '/auth/signup'
    | '/api/auth/$'
    | '/api/ingest/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  appPantryRoute: typeof appPantryRoute
  appProfileRoute: typeof appProfileRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiIngestSplatRoute: typeof ApiIngestSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/pantry': {
      id: '/(app)/pantry'
      path: '/pantry'
      fullPath: '/pantry'
      preLoaderRoute: typeof appPantryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/profile': {
      id: '/(app)/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof appProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ingest/$': {
      id: '/api/ingest/$'
      path: '/api/ingest/$'
      fullPath: '/api/ingest/$'
      preLoaderRoute: typeof ApiIngestSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  appPantryRoute: appPantryRoute,
  appProfileRoute: appProfileRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiIngestSplatRoute: ApiIngestSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
